version: "3"
services:
  app:
    build:
      context: ./docker/php
      args:
        - TZ=${TZ}
        - IMAGE_PHP_VERSION=${IMAGE_PHP_VERSION}
    volumes:
      - ${APP_DIR}:/var/www
      - ./log/php:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}
      - XDEBUG_REMOTE_ENABLE=${XDEBUG_REMOTE_ENABLE}
      - XDEBUG_REMOTE_ADDRESS=${XDEBUG_REMOTE_ADDRESS}

  web:
    build:
      context: ./docker/nginx
    depends_on:
      - app
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ${APP_DIR}:/var/www
      - ./log/nginx:/var/log/nginx
    environment:
      - TZ=${TZ}
      - DOCUMENT_ROOT=${DOCUMENT_ROOT}
    working_dir: /var/www/${DOCUMENT_ROOT}

  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./log/:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}

volumes:
  db-store:
