service: twitter-counter-api-aggregator

provider:
  name: aws
  region: ap-northeast-1
  runtime: provided
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource:
        - "*"

plugins:
  - ./vendor/bref/bref

functions:
  aggregator:
    handler: index.php
    description: ""
    layers:
      - ${bref:layer.php-74}
    events:
      - schedule: "cron(*/30 * * * ? *)"
    environment:
      APP_ENV: faas
      LOG_CHANNEL: stderr
      CONSUMER_KEY: ${env:CONSUMER_KEY}
      CONSUMER_SECRET: ${env:CONSUMER_SECRET}

# Exclude files from deployment
package:
  exclude:
    - "tests/**"
