service: twitter-count-aggregator

provider:
  name: aws
  region: ap-northeast-1
  runtime: provided
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource:
        - "*"

custom:
  alerts:
    stages:
      - dev
      - production
      - staging

    dashboards: true

    topics:
      alarm:
        ${self:service}-${opt:stage}-alerts-alarm
      ok:
        ${self:service}-${opt:stage}-alerts-ok
    alarms:
      - functionErrors
    definitions:
      functionErrors:
        period: 3600

plugins:
  - serverless-plugin-aws-alerts
  - ./vendor/bref/bref

functions:
  aggregator:
    handler: index.php
    description: ""
    layers:
      - ${bref:layer.php-74}
    events:
      - schedule: "cron(*/30 * * * ? *)"
    environment:
      APP_ENV: faas
      LOG_CHANNEL: stderr
      CONSUMER_KEY: ${env:CONSUMER_KEY}
      CONSUMER_SECRET: ${env:CONSUMER_SECRET}
      AWS_BUCKET: ${env:AWS_BUCKET}

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:AWS_BUCKET}
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000

# Exclude files from deployment
package:
  exclude:
    - "tests/**"
