@startuml

package TweetSearchAggregateResultApi{

class tweet検索集計結果APIコレクション {
 + 登録(tweet検索集計結果API)
 + 読込(tweet検索集計結果APIのID): tweet検索条件
}

class tweet検索集計結果API {
  + エンドポイント名
  + 検索対象twitterアカウントユーザー名: string
  + 検索キーワード: string[]
}

tweet検索集計結果APIコレクション o-- tweet検索集計結果API

}

package Tweet {

class tweet {
  + 日時
}

class tweetコレクション{
  + 件数: number
  + 取得(tweet検索条件)
}

tweetコレクション o-d- tweet

class tweet検索期間{
  + 開始日
  + 終了日
}

class tweet検索条件{
  + マッチ条件
  + twitter検索期間
}

class マッチ条件 {
  + 検索対象twitterアカウントユーザー名: string
  + 検索キーワード: string[]
}

tweet検索条件 o-- マッチ条件
tweet検索条件 o-- tweet検索期間

}

tweet検索集計結果API -- tweet検索条件



package TweetAggregateResult{

class tweet検索集計結果
tweet検索集計結果 o-- tweet検索条件
tweetコレクション -r- tweet検索集計結果
class 日次tweet数 {
  + 年月日
  + 件数
}

tweet検索集計結果 o-d- 日次tweet数

}

tweet検索条件 -- tweetコレクション

tweet検索集計結果API -- tweet検索集計結果


@enduml
