name: Laravel

on:
  push:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        options: --health-cmd "AWS_ACCESS_KEY_ID=fake AWS_SECRET_ACCESS_KEY=fake aws --endpoint-url=http://localhost:4566 s3 ls" --health-interval 3s --health-timeout 3s --health-retries 10
        env:
          LOCALSTACK_SERVICES: s3,dynamodb

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: cp .env.example .env
        working-directory: app
      - name: name resolution
        run: |
          echo '127.0.0.1 localstack' | sudo tee -a /etc/hosts
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        working-directory: app
      - name: Generate key
        run: php artisan key:generate
        working-directory: app
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        working-directory: app
      - name: Execute static analysis via Larastan
        run: vendor/bin/phpstan analyse
        working-directory: app
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
        working-directory: app
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      - name: deploy
        run: |
          sudo npm i -g serverless serverless-plugin-aws-alerts
          serverless deploy -v
        working-directory: app
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
